### ISSUE TITLE
bug(web): scrollbars visible

### ISSUE THREAD

**Issue by McPizza0** [un/inbox#100]
scrollbars are visible and ugly in many parts of the app
we're using tailwind and need to resolve this

some examples:
![image](https://github.com/un/inbox/assets/17185737/166acd62-83fb-48da-a2c6-9e89d8645a68)
![image](https://github.com/un/inbox/assets/17185737/37036c27-13be-45e0-8535-962ba53595d1)

**Comment by BlankParticle** [comment]
> Yes, i was making a fix for this in my pr

Sorry if you were working on it, but you haven't said anything in 5 days. We need to move fast, so I fixed it myself.
