### ISSUE TITLE
chore(Web): Add document titles to each page

### ISSUE THREAD

**Issue by BlankParticle** [un/inbox#215]
Add document tittles to each page, indicating information about the page/convo

**Comment by mit-27** [comment]
Hello, I would like to work on this issue. Also, It would be great if you could provide a bit more details about the issue. Thanks!

**Comment by BlankParticle** [comment]
Hey! Thanks for your interest in this issue.
This issue needs to add proper title to each pages. For now all pages are called `Uninbox`.
What we want is to show `Uninbox`, `Settings`, `${ConvoSubject}`, `Org Settings` etc on different pages.
If you are interested in that and can work your way out with Vue/Nuxt, I would be happy to assign you.

If you need any help, Join our discord!

**Comment by mit-27** [comment]
I would love to work on this issue. Thanks
