### ISSUE TITLE
Enhance error message for org shortcodes when using capital letters

### ISSUE THREAD

**Issue by joswayski** [un/inbox#260]
Heyo from Twitter 👋 

Nice launch :) 

I'm leaving this note here because it's too late for me too leave a PR with proper testing and such but, when creating an org shortcode, the error message could be improved when a user puts in capital letter:
![CleanShot 2024-04-08 at 01 44 57@2x](https://github.com/un/inbox/assets/22891173/41415ebf-eb5f-41a5-a063-49dafb42f3f2)

![CleanShot 2024-04-08 at 01 43 22@2x](https://github.com/un/inbox/assets/22891173/8bde9722-0be4-4f9d-8109-da643575e058)

1. https://github.com/un/inbox/blob/7245ac572f9265557d201fc29e6d9914df9c5de7/apps/web-app/pages/join/org.vue#L273
2. https://github.com/un/inbox/blob/7245ac572f9265557d201fc29e6d9914df9c5de7/apps/web-app/pages/%5BorgShortcode%5D/settings/org/new.vue#L142

Either allow [a-zA-Z0-9] and .lowereCase() after or another regex for capital letters only with a different error message 

:)

**Comment by BlankParticle** [comment]
Hey thanks for reporting this issue, we will improve the error message. The orgShortcode is supposed to be small letters and numbers only
