### ISSUE TITLE
fix(web-app): recover my account is not working

### ISSUE THREAD

**Issue by leog** [un/inbox#308]
When presented with login screen there is a "Recover my account" button which doesn't seem to be working.

<kbd><img width="395" alt="image" src="https://github.com/un/inbox/assets/467258/7a64d8a1-8dcf-4988-b2f3-579be90d008a"></kbd>

**Comment by BlankParticle** [comment]
We haven't implemented it yet, If you are locked out of your account contact us on discord, we will help you out
