### ISSUE TITLE
typo

### ISSUE THREAD

**Issue by Aashish-Upadhyay-101** [un/inbox#310]
during account creation step-3

<img width="543" alt="Screenshot 2024-04-12 at 10 59 26 PM" src="https://github.com/un/inbox/assets/81024263/0506f3de-6b26-497e-90f6-b1796b0ce228">

you will not be able to recover your your account.
there are two "your"

**Comment by McPizza0** [comment]
well spotted

**Comment by fahadshahbaz** [comment]
@McPizza0 Can you assign me this?
