### ISSUE TITLE
chore/fix/feature(web): Switch to React + Next 🫡

### ISSUE THREAD

**Issue by McPizza0** [un/inbox#317]
Our core webapp is currently built in Vue/Nuxt with 99% CSR

after much feedback from the community and contributors, we have decided to move to React/Next

This issue is for tracking all the related efforts

If you would like to help out with this, please comment here or pick an issue with the react/next label

@BlankParticle is leading the efforts here

**Comment by rushatgabhane** [comment]
Sounds interesting! @BlankParticle I'd love to help on this issue

**Comment by BlankParticle** [comment]
> Sounds interesting! @BlankParticle I'd love to help on this issue

Hey join our discord server, we are discussing it there

**Comment by rushatgabhane** [comment]
don't mean to be a distration, but i pitched react native on discord
