### ISSUE TITLE
fix(platform): account db column "pre_account"

### ISSUE THREAD

**Issue by McPizza0** [un/inbox#319]
Either use in logic or remove from db

**Comment by McPizza0** [comment]
@BlankParticle can you confirm if this is used or not?

**Comment by BlankParticle** [comment]
> @BlankParticle can you confirm if this is used or not?

I can confirm this is not used
it is fetched in `accountRouter` but never used
also while we are at it, we can also remove `accountCredentials` table as we have moved the data while we did the launch

**Comment by BlankParticle** [comment]
fixed by #763
