### ISSUE TITLE
fix(web): Different Icon / Email Icons in UI

### ISSUE THREAD

**Issue by Flo4604** [un/inbox#358]
![45490](https://github.com/un/inbox/assets/53355483/762860c3-2b20-4751-9406-fac8163281d9)
![47796](https://github.com/un/inbox/assets/53355483/a3382180-05ee-4d8c-b971-d796519641ce)

![image](https://github.com/un/inbox/assets/53355483/c77ec6af-b1bc-400f-bbec-0eccd35fe558)

**Comment by Flo4604** [comment]
Would like to take this on

**Comment by McPizza0** [comment]
this will be implemented in new design, closing this issue
