### ISSUE TITLE
migrate(react/next): Settings: Personal > Security

### ISSUE THREAD

**Issue by McPizza0** [un/inbox#389]
This is part of the migration from Nuxt to Next
Please check the project here: https://github.com/orgs/un/projects/3?pane=info

## What this issue covers

migrating `apps/web-app/pages/[orgShortcode]/settings/user/security.vue`

## Resources

All Next items should be created in the `/apps/web/` folder
the source of the nuxt versions is in `/apps/web-app/`
For now this is a 1:1 migration from Nuxt - small code improvements/bug fixes can be included, but please open separate issues for larger re-factors.

The "Platform" backend should not be modified since we'll be running Nuxt and Next in parallel for a while

We'll be using the Radix theme for standard components: https://www.radix-ui.com/
with Radix Colors throughout the app: https://www.radix-ui.com/colors
The radix primitives are also installed, so we can use ShadCN components where they're more suitable: https://ui.shadcn.com/

## Instructions

Check the item type and status in the issue sidebar:
![image](https://github.com/un/inbox/assets/17185737/5dbb47ca-289f-4255-990d-663cd8a69b0d)

If you want to work on this item, please Comment here
You will not be assigned till you open a draft PR
If your draft PR hasnt had any commits for more than 7 days, you will be unassigned

**Comment by rushatgabhane** [comment]
hey, i want to work on this issue

**Comment by BlankParticle** [comment]
> hey, i want to work on this issue

Hey, thanks for your interest. I have done some work on the page already. You can take it from there, please work on adding other features from the vue version and open a draft PR to be assigned to this issue.
Join our discord for any help you need.

**Comment by McPizza0** [comment]
closing to track elsewhere
