### ISSUE TITLE
when convo is hidden, delete prompt should say "unhide"

### ISSUE THREAD

**Issue by McPizza0** [un/inbox#430]
the delete modal button always says "hide instead"

it need to be dynamic since the convo is already hidden and we need to change the button to "unhide" instead

https://discord.com/channels/1113119653246545961/1232031119415971840/1232031119415971840

**Comment by McPizza0** [comment]
lets fix this in react version not nuxt

**Comment by BlankParticle** [comment]
already fixed, deleting hidden prompt shouldnt show a option to unhide, it shows only delete button now
