### ISSUE TITLE
avatar upload component = fugly

### ISSUE THREAD

**Issue by McPizza0** [un/inbox#44]
the current avatar upload components are fugly
![image](https://github.com/uninbox/UnInbox/assets/17185737/fe39f979-a69c-4ef5-b56a-b8ac90dba330)

across the app we use round avatars, the current implementation is from legacy code/design

we need a new avatar/upload component that shows existing/blank avatar and a button to upload the avatar
please submit examples/designs before working on this issue

places to change:
`/apps/web-app/pages/[orgSlug]/settings/org/index.vue`
`/apps/web-app/pages/[orgSlug]/settings/user/profiles.vue`
`/apps/web-app/pages/join/profile.vue`

**Comment by Praashh** [comment]
Hey @McPizza0 can I work on that issue?

**Comment by McPizza0** [comment]
@Praashh are you working on this?
others would like to take it on

**Comment by Praashh** [comment]
@McPizza0 I am not able to get the passkey. I asked the same doubt on the discord as well, can't able figure out the solution.

**Comment by McPizza0** [comment]
ah, thats ok
ill assign this to someone else till we get your passkey issue sorted

@adityadeshlahre i think you mentioned you wanted to do this?

**Comment by adityadeshlahre** [comment]
Yes, @McPizza0 would like to work on it :slightly_smiling_face: !

**Comment by ezra-en** [comment]
Hey @adityadeshlahre! Do you happen to have a design mock-up for us to check out? I'd love to see the progress you've got so far!

**Comment by BlankParticle** [comment]
has been fixed in react version
