### ISSUE TITLE
add "delete account"

### ISSUE THREAD

**Issue by McPizza0** [un/inbox#442]
If the use is the owner of the org, then we have to enforce deleting the whole org with all org members and all data

if the user is not the owner of the org, then we only set their org membership to "removed" with no data deleting

**Comment by Ankur1493** [comment]
Are we looking to create this in next js web?

**Comment by Ankur1493** [comment]
We can add this in org Profile and user Profile respectively, and also add a confirmation modal

**Comment by BlankParticle** [comment]
fixed in #649
