### ISSUE TITLE
add project wide tsconfig

### ISSUE THREAD

**Issue by McPizza0** [un/inbox#47]
rules:
noUncheckedIndexedAccess: true

**Comment by McPizza0** [comment]
@adityadeshlahre this issue is assigned to me and @cstrnt as we still need to check the best way to implement this
if you know of a solution, im happy to hear it

remember this is a monorepo with lots of sub apps/packages, so it needs to be applied/imported everywhere

**Comment by ezra-en** [comment]
We're using Turborepo, what's stopping us from adopting this method? https://turbo.build/repo/docs/handbook/linting/typescript#sharing-tsconfigjson

**Comment by McPizza0** [comment]
> what's stopping us from adopting this method?
Nothing technical
Would need to import it into all other packages and apps
and get their tsconfigs to extend the root one

**Comment by xMohamd** [comment]
I'll try to work on it next weekend
