### ISSUE TITLE
feature(web): New Convo Nextjs Design

### ISSUE THREAD

**Issue by McPizza0** [un/inbox#494]
PLEASE ENSURE YOU TEST THE EXISTING NUXT VERSION TO UNDERSTAND THE DROPDOWN FLOW

We need to update the "new convo" page
We should put the new convo into a new ShadCN Drawer component that lives in the bottom right hand corner of the window (floating above all other page content)
On mobile, this should use the same drawer component but from the bottom

IF a user has inputted data into the new convo component, but clicks outside or closes it. the data should remain intact

when the user creates the new convo, they should be navigated to that new convo page

this issue will also require creating a new searchable dropdown component.
this will show the teams, org_members and contacts for the org
and provide searchability

Designs to implement (subject to slight change)
![Frame 1597880844](https://github.com/un/inbox/assets/17185737/2b702b12-a83f-4f9a-bada-cfe6dfb6b71d)
![Frame 1597880846](https://github.com/un/inbox/assets/17185737/97b97542-f5d0-4af8-8964-a4b3cefce85d)
![Frame 1597880845](https://github.com/un/inbox/assets/17185737/59d51cb1-eb82-4a34-be5b-6364385c3175)
![Frame 1597880839](https://github.com/un/inbox/assets/17185737/6da7fcde-54f9-4ca4-afbd-b349e21ffac9)
![Frame 1597880843](https://github.com/un/inbox/assets/17185737/c209e1d0-27ce-42d3-a437-96fd92b7c3c1)
![Frame 1597880840](https://github.com/un/inbox/assets/17185737/4a325888-9a93-4c94-b35a-8f8c68641b70)
![Frame 1597880842](https://github.com/un/inbox/assets/17185737/be89bdc8-39dc-449e-9b6c-02de2f654ee6)
![Frame 1597880841](https://github.com/un/inbox/assets/17185737/72864a1a-f49c-40e9-b278-57365341b39d)

**Comment by Aashish-Upadhyay-101** [comment]
I would like to work on this. 🚀

**Comment by McPizza0** [comment]
sure!

we dont assign issues till there is a draft pr with progress attached.

please reach out with any questions

**Comment by Aashish-Upadhyay-101** [comment]
@McPizza0 
I think Shadcn sheet component will also look good here.

**Comment by McPizza0** [comment]
> @McPizza0 I think Shadcn sheet component will also look good here.

yes, so long as it dosnt interfere with the rest of the screen, and reuses the same design as the drawer component

users should be able to have the new convo open, and still navigate around the app to copy text etc.
