### ISSUE TITLE
nextjs: new convo participants missing contacts

### ISSUE THREAD

**Issue by McPizza0** [un/inbox#513]
contacts are not showing in the dropdown when selecting convo participants
this is a regression from the nuxt version
![image](https://github.com/un/inbox/assets/17185737/2eed8611-94a2-49e3-aa2a-d9882d1712ee)

**Comment by askadityapandey** [comment]
HEY, I was trying to fix this issue. I'm kinda stuck like in this `apps/web-app/components/un/ui-dropdown.vue` component, I am lil confused if this issue comes from this component or not.

**Comment by McPizza0** [comment]
hey @askadityapandey !
thanks for your interest
sorry, this was related to our nextJS port, and has already been solved. looks like I made duplicate issue and didnt close this one

for reference, most issues are now for the app in `apps/web/` (new nextjs version) and not `apps/web-app/` (old nuxtjs version)
