### ISSUE TITLE
Next: when signing up, cant save profile without adding avatar

### ISSUE THREAD

**Issue by McPizza0** [un/inbox#549]
when signing up
if you only change the user profiles' name fields
the "Next" button does not become active

![CleanShot 2024-07-08 at 17 53 12@2x](https://github.com/un/inbox/assets/17185737/1318913c-05c2-43e2-ba57-3c81a0c959b4)

**Comment by rockingrohit9639** [comment]
@McPizza0 @BlankParticle Can I work on this issue ?

**Comment by BlankParticle** [comment]
Yes, you need to make a draft PR first then we will assign you to the issue.

**Comment by rockingrohit9639** [comment]
@BlankParticle I have created this PR - #561
