### ISSUE TITLE
Hiding/un-hiding convo fix

### ISSUE THREAD

**Issue by yash-kh** [un/inbox#564]
Whenever we hide and un-hide a convo, it crated duplicate entries in respective list.

![image](https://github.com/user-attachments/assets/319bceba-c0ae-4060-98e4-d08a9fd4262b)

**Comment by BlankParticle** [comment]
It took me little long to understand the issue you are reporting.
Can you replace the image with a screenshot showing the duplicated entires for documenting the issue a bit better

**Comment by yash-kh** [comment]
Looks like the `useToggleConvoHidden$Cache` ran twice that is making two entries, here is the video for reference, it's making 2 entries of save convo in the UI.

https://github.com/user-attachments/assets/167fa61c-a1ec-487b-854c-69ac886f893b
