### ISSUE TITLE
when creating new org, not redirected correctly

### ISSUE THREAD

**Issue by McPizza0** [un/inbox#566]
when a user is already a member of an org
and creates a new org using the org switcher
after setting their profile
the user is redirected back to their existing default org instead of the new organization

we should redirect the user back to the new org based on orgShortcode

**Comment by McPizza0** [comment]
also, the list of orgs in the menu is not updates with the new org
![CleanShot 2024-07-15 at 15 30 20@2x](https://github.com/user-attachments/assets/5e16c7b3-b30e-4f52-9d74-43ba37549f8f)

@BlankParticle do we have a hook for this that you could share?

**Comment by BlankParticle** [comment]
was it fixed in #578?
That PR doesn't link any issue but looks like it fixes this.

**Comment by yash-kh** [comment]
Yeah, I also checked it's working.

**Comment by BlankParticle** [comment]
Closing this issue as completed
