### ISSUE TITLE
feature: Allow Deleting/Hiding of multiple conversations at the same time

### ISSUE THREAD

**Issue by Flo4604** [un/inbox#590]
I as a User want to be able to delete/hide multiple conversations by selecting multiple of them and then pressing a delete / hide button. 

A idea on this: 

Have a checkbox on the left side, once a single checkbox is selected you show a toolbar which shows delete / hide.

**Comment by yash-kh** [comment]
@BlankParticle are you working on it or can i take this up?

**Comment by BlankParticle** [comment]
I am working on it,there is a open draft
