### ISSUE TITLE
error when adding sub domain

### ISSUE THREAD

**Issue by McPizza0** [un/inbox#62]
when adding a new domain, we use the `createNewDomain` procedure in `apps/web-app/server/trpc/routers/orgRouter/mail/domainsRouter.ts`

this validates the domain actually exists by trying to resolve the name servers for the input domain name.
it is assumed that every single registered domain has nameservers set.

```ts
      await dns.promises.resolveNs(domainName).catch(() => {
        throw new TRPCError({
          code: 'FORBIDDEN',
          message: 'Domain does not exist or is not registered'
        });
      });
```

subdomains do not have their own nameservers and this the error is thrown

fix:

ideally, if the input domain contains more than one `.` we would split it at the first occurring `.` and keep going till theres only 1 `.` left. if still no results, then throw the error

potential issues:
this could throw some false positives when the input is `domain.co.uk` (a valid domain) since its also possible to register `domain.uk` and `co.uk` has some name servers

mitigation:
domains will not be available for sending till dns is verified anyway. and 3 days after adding and not being verified, domains are disabled

thanks @daallgeier for highlighting this issue

**Comment by skushagra9** [comment]
Please assign me , this issue, I am interested

**Comment by McPizza0** [comment]
extensive list of subdomains for reference
https://tld-list.com/tlds-from-a-z

**Comment by McPizza0** [comment]
@BlankParticle found an interesting approach
using Cloudflare's http dns lookups, we can get a `NXDOMAIN` error if a domain is not registered
The error is different if its a subdomain, so this is a valid solution
![image](https://github.com/un/inbox/assets/17185737/842fbd72-6465-43c6-8b9b-04950745b02b)
![image](https://github.com/un/inbox/assets/17185737/64d33f6b-5471-4ea4-9a96-4099b1cede83)
