### ISSUE TITLE
[ENG-131] Org switcher text not truncated

### ISSUE THREAD

**Issue by McPizza0** [un/inbox#688]
Org switcher: when a user or org's name is long, the text is not truncated

![CleanShot 2024-08-13 at 15.54.12@2x.png](https://uploads.linear.app/b5f4b571-8b40-4580-adc5-236adea0bd29/45fc0500-d924-4600-9a1d-1a8e0b1ba2f7/4a5e5324-3661-4c6d-b39a-805109c66c96?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2I1ZjRiNTcxLThiNDAtNDU4MC1hZGM1LTIzNmFkZWEwYmQyOS80NWZjMDUwMC1kOTI0LTQ2MDAtOWExZC0xYThlMGIxYmEyZjcvNGE1ZTUzMjQtMzY2MS00YzZkLWIzOWEtODA1MTA5YzY2Yzk2IiwiaWF0IjoxNzIzNTU3MzA3LCJleHAiOjE3NTUwOTMzMDd9.abkOhOii1QeLZjJBt6begzTY3Hsdf-yMEYg9rTcGVVk)

<sub>From [SyncLinear.com](https://synclinear.com) | [ENG-131](https://linear.app/unn/issue/ENG-131/org-switcher-text-not-truncated)</sub>

**Comment by SySagar** [comment]
Will take up this issue.

**Comment by BlankParticle** [comment]
sure make a pr, I will assign you once the pr is up

**Comment by SySagar** [comment]
@BlankParticle raised a pr. Please check.
