### ISSUE TITLE
[bug]: profile info validation and name splitting

### ISSUE THREAD

**Issue by SySagar** [un/inbox#703]
So there are actualy two bugs here:

1.  If a person with three words in its name enter first two words in first name and last word in last name , then first name is trimmed to first word and rest is put into last name. I think either should me an optino middle name or for now we can keep everything into firstname and last word in last name.

2. If in first name I hit spaces then it counts it as non empty, which seems ok but practically we shouldn't allow , rther have a validation check for it somehow.

https://www.loom.com/share/001481f21a29494c970199da9c87cb70?sid=db739696-5127-4216-938d-670fe135ecb5

**Comment by SySagar** [comment]
@BlankParticle @McPizza0  if this seems a legit issue , I would like to work on it.

**Comment by BlankParticle** [comment]
sure go ahead, make a pr
