### ISSUE TITLE
[ENG-104] new convo without email identity empty field

### ISSUE THREAD

**Issue by McPizza0** [un/inbox#709]
when creating a new convo, without having an email identity assigned to you, the dropdown to select the email identity is empty. we should add an empty state there and also disable adding email participants (contacts or new emails) if the user dosnt have an email identity

![CleanShot 2024-08-06 at 18.32.22@2x.png](https://uploads.linear.app/b5f4b571-8b40-4580-adc5-236adea0bd29/a6b55205-d17c-4350-985a-cfb6c1a7b601/24727b47-e3f0-4a31-bc8c-30488492fcb7?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2I1ZjRiNTcxLThiNDAtNDU4MC1hZGM1LTIzNmFkZWEwYmQyOS9hNmI1NTIwNS1kMTdjLTQzNTAtOTg1YS1jZmI2YzFhN2I2MDEvMjQ3MjdiNDctZTNmMC00YTMxLWJjOGMtMzA0ODg0OTJmY2I3IiwiaWF0IjoxNzI0MDQ5NjYzLCJleHAiOjE3NTU1ODU2NjN9.r28LuwTP71dN4H7L7ABKwIa3Guh1USYHFF1fFxDNJUk)

<sub>From [SyncLinear.com](https://synclinear.com) | [ENG-104](https://linear.app/unn/issue/ENG-104/new-convo-without-email-identity-empty-field)</sub>

**Comment by SySagar** [comment]
Would pick up this issue and fix asap.
