### ISSUE TITLE
[Bug] Org name not changing instantly

### ISSUE THREAD

**Issue by SySagar** [un/inbox#710]
Although this is a minor bug but as u can see on changing and updating profile name it instantly updates it in the sidebar. But this is not the case in org name.

https://www.loom.com/share/0f3e4e92eb6e4d27861b9c635febb303?sid=b221eb23-2527-4b20-a402-fe4f068effb4

**Comment by McPizza0** [comment]
looks like we need to invalidate the query for that

**Comment by BlankParticle** [comment]
can confirm, you can probably make a pr fixing this issue

**Comment by SySagar** [comment]
sure will raise the pr soon.

**Comment by richiemcilroy** [comment]
Fix: https://github.com/un/inbox/pull/737
