### ISSUE TITLE
[Bug] Invalid IP Shown in Session

### ISSUE THREAD

**Issue by Flo4604** [un/inbox#719]
Production shows this: 
![53882](https://github.com/user-attachments/assets/ba0e9db6-6ff8-4100-8840-b5bd3493c5cb)

127.0.0.0 is not my client ip address

**Comment by BlankParticle** [comment]
That is your chrome version which we inferred from your user agent string, not ip

**Comment by Flo4604** [comment]
> That is your chrome version which we inferred from your user agent string, not ip

ah yeah my fault, that makes more sense are there any plans to show the IP address of the session?

**Comment by McPizza0** [comment]
valid issue. it shouldn't show any IP
we don't track any either

**Comment by BlankParticle** [comment]
> valid issue. it shouldn't show any IP we don't track any either

it is not a ip lol,
also we only use ip in elevated mode to prevent cookie hijacking

We are not going to show any ip in the app

**Comment by McPizza0** [comment]
@BlankParticle `127.0.0.1` is a valid ip, its local host ip
this is a valid issue
the string for session name should not show any IP address
regardless whether its local ip, lan ip, or real ip
