### ISSUE TITLE
feat(web-app): User Security Page

### ISSUE THREAD

**Issue by McPizza0** [un/inbox#80]
Once #79 merges, we need to add a new security settings page so users can manage their own security

they should be able to:
- verify their recovery email address (if not verified)
- change their recovery email address
- change their password (if one is set, or set one up if not)
- switch on/off password auth if they have passkeys enabled
- setup TOTP 2FA (separate issue)
- manage their passkeys (add, remove)
- manage their user sessions (destroy session, log out of all devices)

**Comment by skushagra9** [comment]
I am interested to work on this issue
