### ISSUE TITLE
Automatically add naming when adding a passkey

### ISSUE THREAD

**Issue by McPizza0** [un/inbox#83]
When users add a new passkey, we should determine which authenticator created the passkey

to do this we should extract the `aaguid` and do a lookup for the name and icons

here is a great implementation by Hanko: https://github.com/teamhanko/hanko/pull/1303/files#diff-0ee85ca590e4ad6694aa28de2d438ea7184e2fe81f08110e936bae88cd647de9

**Comment by skushagra9** [comment]
We can also add a feature , to allow users enter a nickname for their passkey

**Comment by McPizza0** [comment]
it might add some extra friction when signing up
but maybe good when adding them from inside the app

**Comment by skushagra9** [comment]
makes sense, yes, I have added in the security page
