### ISSUE TITLE
bug(web-app): handle if user does not have org

### ISSUE THREAD

**Issue by McPizza0** [un/inbox#99]
if a user dosnt have a default org (or any org) they will be redirected and get tons of errors

best place to handle this would be in the org redirect: `apps/web-app/pages/redirect.vue`

we have a "new org" form that would be a good candidate as a destination: `/apps/web-app/pages/[orgSlug]/settings/org/new.vue`
but we cant redirect here as its under the `[orgSlug]` folder and would send back to redirect
the new page would need to factor in the auth middleware to ensure users can navigate to it

**Comment by ezra-en** [comment]
Why is new org under an org? 😂 I figure there should be an org-independent settings page where we can sort that out without worrying about all the other org-specific settings

**Comment by McPizza0** [comment]
yeah, agree
it was moved there a while ago when I refactored some other stuff to have orgslugs in the url

it could probably be under `/join/neworg`
that location is already set up for auth middleware stuff
